### ISSUE TITLE
Afficher un message d'erreur si recherche non concluante 

### ISSUE THREAD

**Issue by Clem-mrtn** [betagouv/ecolab-calculateur-fruits-et-legumes-de-saison#1]
Pour tous les fruits/légumes mal orthographiés OU non existants (type avocat, papaye, mangue qui peuvent être rechercher même si c'est pas produit en France) il faudrait peut-être rajouter un message d'erreur !
"Désolée......."

**Comment by florianpanchout** [comment]
@Clem-mrtn Ça nécessiterait d'avoir une liste des produits manquants.

Et si on prends du temps pour créer une liste des produits manquant, autant carrément chercher leur saison et les ajouter non ?

**Comment by martinregner** [comment]
Ok @florianpanchout pour ajoute davantage de F&L. Mais il faut ajouter aussi leurs variantes en termes d'appellation (ça peut être très varié pour la [chayotte / christophine / Chouchou](https://fr.wikipedia.org/wiki/Chayote) par ex. qui pourtant se trouve de plus en plus ...).

Cela pose la question des synonymes ou d'une recherche plus souple : si je tape "carote" je n'ai pas de retour ... certes, j'ai qu'à savoir écrire mais bon, une erreur est si vite arrivée 😉  Une carotte c'est tellement basique que l'utilisateur ne va pas remettre en question sa "carote" et va sortir.

Pour ces différents cas je pense qu'il faudrait qqc du genre "Désolé je n'ai pas trouvé, mais voici les F&L du mois" et hop tu lui affiche quand même ce qu'il y a en ce moment

**Comment by florianpanchout** [comment]
@martinregner @Clem-mrtn Au final je ne suis pas sur que ça soit une bonne idée d'ajouter les fruits et légumes manquants.

L'ADEME a pris le parti pris de ne référencer que les produits locaux (les autres étant trop polluants j'imagine). Du coup il serait peut être plus logique de juste afficher un texte explicatif de cette démarche lorsque l'on cherche un produit manquant ?

**Comment by Clem-mrtn** [comment]
Je comprends mais, je reste persuadée que si le simulateur s'adresse au B2C (au final), y en a pleins qui vont chercher avocat, mangue ... (très "en vogue" en ce moment en plus).
Et je trouverais ça pas mal effectivement, afin de les **sensibiliser**,  d'afficher un message d'erreur " Désolé je n'ai pas trouvé, ce n'est pas de saison mais voici les F&L du mois". 
  => Après on peut tester le calculateur comme ça et on voit les retours :) 

Et effectivement pour les fautes de frappes, je pense qu'il faudrait quand même prévoir un message d'erreur " Désolé ce légume n'existe pas ...". 
Parce que là rien ne s'affiche c'est un peu confusant je trouve

**Comment by martinregner** [comment]
J'ai l'impression qu'on converge, au moins pour cette première version, vers l'idée d'un message lors de fautes de frappe ou légume manquant (ça peut être le même à ce stade). Quelque chose du genre :

"🤔 Désolé je n'ai pas trouvé, ce n'est peut-être très local ? Voici les fruits & légumes du mois"

Qu'en pensez-vous @Clem-mrtn @florianpanchout ?

**Comment by florianpanchout** [comment]
J'ai découpé cette issue pour traiter indépendamment les différents points :

https://github.com/betagouv/ecolab-calculateur-fruits-et-legumes-de-saison/issues/7
https://github.com/betagouv/ecolab-calculateur-fruits-et-legumes-de-saison/issues/8
https://github.com/betagouv/ecolab-calculateur-fruits-et-legumes-de-saison/issues/9
https://github.com/betagouv/ecolab-calculateur-fruits-et-legumes-de-saison/issues/10
https://github.com/betagouv/ecolab-calculateur-fruits-et-legumes-de-saison/issues/11
