### ISSUE TITLE
Iframe - Problème affichage au clic sur un mois

### ISSUE THREAD

**Issue by martinregner** [betagouv/ecolab-calculateur-fruits-et-legumes-de-saison#17]
[Sur Chrome 87]

Au clic sur un mois présent sur la carte d'un F&L donné :
- l'iframe se rallonge avec une hauteur "infinie"
- le fond repasse sur celui par défaut

**Comment by florianpanchout** [comment]
Oups... C'est corrigé !

**Comment by Clem-mrtn** [comment]
Ca marche toujours pas chez moi ! Lorsque j'arrive sur la page le simualteur est "blanc" et quand je clique dessus il s'affiche correctement 
![image](https://user-images.githubusercontent.com/76995768/105499359-a57fed00-5cc1-11eb-9ff8-86acee81cf25.png)

**Comment by florianpanchout** [comment]
@Clem-mrtn Est ce que le problème persiste en navigation privée ?

**Comment by Clem-mrtn** [comment]
En navigation privé, il s'affiche blanc et je ne peux carrément pas cliquer dessus pour qu'il s'affiche correctement (avec le fond jaune).
Mais la capture ci-dessus, j'étais en navigation ouverte et ça s'affichait blanc au chargement, puis jaune quand je cliquais dessus

**Comment by florianpanchout** [comment]
Aaah ok ! Donc c'est normal qu'il s'affiche en blanc :) (pour s'intégrer au "design" du site actuel). Par contre c'était un bug qu'il puisse repasser au thème par défaut au clic sur le titre.

**Comment by Clem-mrtn** [comment]
Aaaah ok !
Oui du coup c'est OK je viens de retester de mon côté on ne passe plus sur l'affichage par défaut au clique 👍

**Comment by martinregner** [comment]
Ok, plus simple de rester juste sur la carte du F&L en question et d'ouvrir le site complet pour plus de détail 👍 

Par contre @florianpanchout, que penserais-tu d'avoir "**Aller plus loin**" ou "**Accéder à la version détaillée**" plutôt que "En savoir plus sur ce simulateur" ?
Je pense que ça fait un CTA plus engageant.

**Comment by florianpanchout** [comment]
Je pensais même remplacer par "En savoir plus sur ce simulateur" qui renverrai vers la page sur le site Datagir

Ce bouton serait aussi sur la version détaillée. Ca permettrait de faire la passerelle entre le simulateur et Datagir pour les réutilisateurs

**Comment by martinregner** [comment]
J'aimais bien l'idée d'un bouton "Accéder à la version détaillée" quand tu es sur l'iframe. Sinon, tu passes à côté de fonctions cools de l'app non ? (affichage par mois notamment)

Pour les réutilisateurs, peut-être un CTA plus petit comme un texte avec du lien plutôt qu'un bouton ?

On pourrait donc avoir 2 CTA distincts : bouton pour utilisateur du simulateur + lien pour réutilisateur / intégrateur du simulateur.
Qu'en penses-tu ?
