### ISSUE TITLE
Rendre les mois cliquables pour afficher les fruits/legumes du mois ?

### ISSUE THREAD

**Issue by Clem-mrtn** [betagouv/ecolab-calculateur-fruits-et-legumes-de-saison#2]
on pourrait envisager lors de la réponse qu'on puisse cliquer sur les mois,  ce qui nous emmènerait sur une liste des fruits/légumes consommables pendant cette période 

Scénario : 
Je rentre tomate
Réponse Non (Janvier rouge, février rouge....)
Je clique sur Janvier : reconduit sur une liste des produits que je peux consommer ce mois-ci

**Comment by florianpanchout** [comment]
Done :)
