### ISSUE TITLE
Emoji exemples de saison seulement ?

### ISSUE THREAD

**Issue by martinregner** [betagouv/ecolab-calculateur-fruits-et-legumes-de-saison#22]
Les exemples d'emojis peuvent créer de la confusion ; ex. "je vois cerise en ce moment mais quand je clique c'est rouge"
![image](https://user-images.githubusercontent.com/46482115/105831273-ccdb0080-5fc6-11eb-87ce-3051ac6699c2.png)

Serait-il possible d'avoir des émojis proposés qui correspondent au mois en cours ? Ca permettrait d'avoir une sorte de nudge pour orienter vers des bons choix pour chaque saison

**Comment by florianpanchout** [comment]
C'est fait :)

**Comment by martinregner** [comment]
Top !! 👍
