### ISSUE TITLE
Afficher le CO2 seulement en saison

### ISSUE THREAD

**Issue by martinregner** [betagouv/ecolab-calculateur-fruits-et-legumes-de-saison#23]
Les scores CO2 sont modélisé pour des produits moyens principalement en saison. En cliquant sur un F ou L hors saison, on voit donc son score en pensant que c'est son score "actuel".

Propositions : 
- Afficher le CO2 seulement quand on entre dans les mois de saison de chaque F ou L
- Griser le CO2 lorsque l'on est hors saison, en précisant que c'est le CO2 pour la valeur de saison

Cas particuliers : tomate et fraise
Le score actuel est le moyen annuel. Serait-il possible d'afficher : 
- en saison le CO2 de saison ?
- hors saison le CO2 hors saison ?

**Comment by florianpanchout** [comment]
@martinregner Est on sur que les valeurs sont pour des produits en saison ? Et non pas une moyenne ?

**Comment by florianpanchout** [comment]
J'ai enlevé l'affichage. Ça me semble être le plus clair

**Comment by martinregner** [comment]
>  Est on sur que les valeurs sont pour des produits en saison ? Et non pas une moyenne ?

Oui c'est après discussion avec Vincent qu'on a proposé ce changement (c'est un peu moins binaire que ça, mais globalement c'est comme ça pour la majorité des F&L)
