### ISSUE TITLE
Affichage local uniquement en saison

### ISSUE THREAD

**Issue by martinregner** [betagouv/ecolab-calculateur-fruits-et-legumes-de-saison#24]
Lorsqu'on affiche un F ou L hors saison, on peut voir un **Non** rouge + un **local** vert. C'est confusant, et possiblement trompeur : en regardant rapidement on peut croire que même hors saison on peut trouver ce F ou L localement, ce qui n'est pas le message que l'on veut faire passer.

Je propose de n'afficher la localité du produit que lors des mois de saison.
Ou éventuellement, selon choix dans #23, griser en hors saison.

Qu'en penses-tu ?

**Comment by florianpanchout** [comment]
J'ai enlevé l'affichage
