### ISSUE TITLE
Bouton "En savoir plus sur ce simulateur" ne fonctionne plus

### ISSUE THREAD

**Issue by martinregner** [betagouv/ecolab-calculateur-fruits-et-legumes-de-saison#26]
Le bouton "En savoir plus sur ce simulateur" ne fonctionne plus sur l'embed, ex ici :
https://agirpourlatransition.ademe.fr/particuliers/conso/alimentation/limpact-alimentation-lenvironnement

**Comment by florianpanchout** [comment]
Corrigé
