### ISSUE TITLE
Affichage sur Edge

### ISSUE THREAD

**Issue by martinregner** [betagouv/ecolab-calculateur-fruits-et-legumes-de-saison#28]
Une utilisatrice nous fait part de quelques (mini) bugs sur Edge :
- toutes les icônes de fruits et légumes ne s’affichent pas :
![image](https://user-images.githubusercontent.com/46482115/108498185-ccbfdf00-72ac-11eb-981d-d26be9a37418.png)

- UX : certains contrastes ne sont pas accessibles 
![image](https://user-images.githubusercontent.com/46482115/108498297-f5e06f80-72ac-11eb-8d3d-eb42b42113b2.png)

**Comment by laem** [comment]
A garder en tête : https://9to5google.com/2020/08/18/microsoft-edge-legacy-replaced-chromium

En gros, le vieux Edge n'a plus que deux mois.

![image](https://user-images.githubusercontent.com/1177762/108586565-98e9c580-734f-11eb-86f7-70998d7ae490.png)

**Comment by florianpanchout** [comment]
Corrigé pour les emojis

Pour les couleurs non accessible, c'est pour ça qu'il y a un thème accessible sur chaque simulateur. Peut être faut il le mettre plus en avant ?

**Comment by martinregner** [comment]
@florianpanchout le thème n'est accessible qu'à l'intégration non ? On peut laisser le choix à chaque site.
Sur le simulateur général, peut-être un petit lien tout en bas qui affiche le simulateur en "Version accessible" ?

**Comment by florianpanchout** [comment]
C'est fait

**Comment by martinregner** [comment]
Top !!
C'est voulu que le là ce soit à gauche, et sur le site pour le darkmode ce soit à droite ? (just asking 😉)

**Comment by florianpanchout** [comment]
Sur le site j'ai respecté le sens de lecture logique gauche => droite.

Sur les simulateurs il y a plus souvent du contenu à droite (surtout sur impact transport en fait), du coup je l'ai mis à gauche pour qu'il n'interfère pas visuellement. Mais c'est vrai qu'il me semblerait peut être mieux placé à droite finalement. 

Tu en penses quoi ?

**Comment by martinregner** [comment]
"intuitivement" j'ai l'impression que c'est plutôt à droite que l'on retrouve ce type d'option. En cherchant un peu, j'ai pas trouvé beaucoup d'exemples mais c'était en haut à droite à chaque fois.

**Comment by florianpanchout** [comment]
Pareil. Je l'ai mis à gauche sur tous les simulateurs du coup

**Comment by martinregner** [comment]
A droite non ? ;)
Parfait !

**Comment by florianpanchout** [comment]
Ahaha ces notions ont toujours été très floues pour moi...
