### ISSUE TITLE
Favicon parfois mal compris

### ISSUE THREAD

**Issue by martinregner** [betagouv/ecolab-calculateur-fruits-et-legumes-de-saison#29]
Le "simple carré jaune" semble parfois poser question.
> Le favicon est juste un carré jaune (je ne sais pas si c’est fait exprès)

Peut-être simplement ajouter le "A" Datagir à l'intérieur ? ou une déclinaison du favicon Datagir avec la couleur à droite du simulateur ? (je ne sais pas si ça marche visuellement avec les couleurs des 3 simulateurs...)
ex :

![image](https://user-images.githubusercontent.com/46482115/108498805-b49c8f80-72ad-11eb-9204-da57e9b3ec5d.png)

**Comment by florianpanchout** [comment]
J'ai mis le A bicolore sur mfls et mcc

**Comment by martinregner** [comment]
top, ça rend bien je trouve !
