### ISSUE TITLE
"Voir tous les produits de saison" - Redirection plutôt vers le calendrier de saison de l'ADEME

### ISSUE THREAD

**Issue by Clem-mrtn** [betagouv/ecolab-calculateur-fruits-et-legumes-de-saison#3]
Au lieu de recréer une liste, rediriger vers le beau calendrier de l'ADEME https://www.ademe.fr/sites/default/files/assets/documents/calendrier-fruits-legumes-de-saison.pdf

**Comment by florianpanchout** [comment]
@Clem-mrtn Dommage de sortir du site non ? 

Et il ne répond pas précisément à cette question : 
https://startups-detat.slack.com/archives/CFC5PRCNA/p1610633696003000?thread_ts=1610633597.002500&cid=CFC5PRCNA

Ici on veut pouvoir voir directement les produits consommables actuellement

**Comment by martinregner** [comment]
Pour la suggestion de @Clem-mrtn que je trouve aussi intéressante, je propose un bouton du genre "Imprimer le calendrier pour le mettre sur mon frigo" avec le lien vers le calendrier en pdf

Sinon @florianpanchout : on pourrait demander dans le champ de recherche "Rentrez un mois, un fruit ou un légume" ?

**Comment by florianpanchout** [comment]
Done
