### ISSUE TITLE
Mise à jour Footer

### ISSUE THREAD

**Issue by florianpanchout** [betagouv/ecolab-calculateur-fruits-et-legumes-de-saison#31]
@martinregner J'ai mis à jour le simulateur avec le nouveau footer, partage, contact, etc...

**Comment by martinregner** [comment]
Bizarre mon commentaire a disparu ^^

Je disais, petit problème d'affichage des menus déroulants sur :
- l'intégration
- le partage


![image](https://user-images.githubusercontent.com/46482115/115428679-ec1eae00-a202-11eb-94d4-d737ea5e3007.png)

**Comment by florianpanchout** [comment]
C'est corrigé !
