### ISSUE TITLE
Toolkit pour téléchargement mobile : "Installer l'application" 

### ISSUE THREAD

**Issue by Clem-mrtn** [betagouv/ecolab-calculateur-fruits-et-legumes-de-saison#33]
Un truc comme tu proposais pour pouvoir télécharger l'application sur : Safari 
Et sur Firefox ? (à voir si c'est necessaire d'y passer du temps vu le nb d'utilisations) 

![image](https://user-images.githubusercontent.com/76995768/116876518-e79fbf80-ac1c-11eb-8af0-a803bce939d2.png)

**Comment by florianpanchout** [comment]
Done
