### ISSUE TITLE
Idée iframe saison : impact tomate et fraise hors saison

### ISSUE THREAD

**Issue by martinregner** [betagouv/ecolab-calculateur-fruits-et-legumes-de-saison#4]
On pourrait ajouter une petite info complémentaire pour quelques F&L, par ex. (textes à raccourcir si besoin) :
- une [fraise hors saison](https://www.agribalyse.fr/app/aliments/13014_2#Fraise_hors_saison,_crue) c'est +43% d'émissions de CO2 par rapport à une [fraise de saison](https://www.agribalyse.fr/app/aliments/13014_1#Fraise_de_saison,_crue)
- une [tomate hors saison](https://www.agribalyse.fr/app/aliments/20047_2#Tomate_hors_saison,_crue) a 3 fois plus d'impact sur l'environnement qu'une [tomate de saison](https://www.agribalyse.fr/app/aliments/20047_1#Tomate_de_saison,_crue) (+370 % d'émissions de CO2 !)
- un haricot vert a émis 21 fois plus de CO2 pour arriver dans votre assiette quand il est [importé par avion](https://www.agribalyse.fr/app/aliments/20061_1#Haricot_vert_import%C3%A9_par_avion,_cru) !

**Comment by martinregner** [comment]
Oui pas de soucis @florianpanchout c'est du plus mais une première version peut très bien sortir sans !

Surtout que là pour l'instant la fraise se la ramène à chaque F&L 😋  ... il vaut mieux le retirer je trouve ça perturbant ;)

**Comment by florianpanchout** [comment]
Texte retiré
