### ISSUE TITLE
Raccourcis emoji F&L sous la barre de recherche

### ISSUE THREAD

**Issue by martinregner** [betagouv/ecolab-calculateur-fruits-et-legumes-de-saison#5]
J'ai mis un petit moment (3-4 utilisations) à voir que les emojis sous la barre de recherche n'était pas juste pour la déco 😋 (c'est l'effet d'animation p-e qui m'a rappelé celui d'Agribalyse 🥕 ;)

Que penses-tu d'ajouter un "Exemples :" ou "Les plus recherchés :" pour inciter au clic ?

**Comment by florianpanchout** [comment]
J'ai ajouté une animation pour attirer l'attention sur les suggestions

**Comment by martinregner** [comment]
Ah bien ! Tu peux l'accélérer un peu ? J'ai eu du mal à la voir au début j'avoue ;)

**Comment by florianpanchout** [comment]
C'est mieux ?
