### ISSUE TITLE
Vérifier textes et chiffres

### ISSUE THREAD

**Issue by florianpanchout** [betagouv/ecolab-calculateur-fruits-et-legumes-de-saison#6]
Je me suis basé sur les émissions CO2E de la tomate et de la fraise pour calculer le 256%. Même chose pour le graph.

**Comment by martinregner** [comment]
Je te propose de simplifier en :
- retirant notamment le pourcentage, pas facile à interpréter 
- modifiant la partie sur les fraises issue d'autres chiffres qu'Agribalyse
- pour la dernière partie, introduisant NGC qui permet de dépasser les moyennes et rentrer dans son cas individuel

-----

## 4 fois plus
_Une tomate produite localement, mais sous une serre chauffée, génère environ 4 fois plus de gaz à effet de serre, que la même tomate produite à la bonne saison. Or, nous sommes environ 75% de Français à déclarer consommer des tomates en hiver. De même pour les fraises, 1 kg consommé en hiver génère 40% d'émissions de gaz à effet de serre de plus que la même quantité produite en saison. Bénéfiques pour le climat et la santé, les fruits et légumes de saison sont également meilleurs au goût._

-----

_L’alimentation est le premier poste d’émission de gaz à effet de serre, en France, devant les transports et le logement. Or, c’est un domaine dans lequel chacun dispose d’une capacité d’action : comme manger de saison, il existe de nombreuses solutions simples et concrètes pour limiter ces émissions. [Découvrez comment aller plus loin](http://nosgestesclimat.fr/) !_

**Comment by florianpanchout** [comment]
Je trouve que le pourcentage apporte en terme de présentation. Je ne peux pas afficher un "4 fois plus" en gros. Sinon pour le reste j'ai repris en restructurant un peu

**Comment by martinregner** [comment]
Le pourcentage est réalisé juste sur 2 fruits, et n'a pas de sens de manière généralisée (le risque est qu'il soit compris et repris comme "en moyenne un F ou L de hors saison c'est 256% de plus..." ce qui est faux).

Pour avoir une petite animation, est-ce que tu peux faire un petit compteur juste sur le 4 ? :)
> ## 4 fois plus

Ca peut aussi être "Jusqu'à 4 fois plus"

Les textes sont un peu longs mais clairs, on peut garder. J'avais juste retiré : 
"_Consommer des fruits et légumes de saison est un excellent moyen de concilier plaisir, santé et climat._"

il fait doublon je trouve avec
"_Bénéfiques pour le climat et la santé, les fruits et légumes de saison sont également meilleurs au goût._"

...non ?

**Comment by florianpanchout** [comment]
C'est vrai que le 256% se base un peu sur du vent aha. J'ai changé :)

**Comment by martinregner** [comment]
Ok top ! :)
