### ISSUE TITLE
Ajout de l'indicateur local

### ISSUE THREAD

**Issue by florianpanchout** [betagouv/ecolab-calculateur-fruits-et-legumes-de-saison#7]
J'ai ajouté un indicateur local / non local (ainsi qu'un texte d'explication) sur les produits

Exemple : 
https://calculateur-fruits-et-legumes.herokuapp.com/?search=betterave
https://calculateur-fruits-et-legumes.herokuapp.com/?search=noix%20de%20coco

Possible de réécrire le texte d'explication ?

**Comment by fjg** [comment]
C'est mieux, en revanche comme le calculateur peut être intégré n'importe où, il serait bon de bien faire figurer local = "France métropolitaine", ca peut être visuellement (carte... et petite popup pour bien le comprendre).
Sur la popup "local", attention à "grande quantité de GES", rapporté au kg de F&L transporté, c'est pas forcément grand justement. @martinregner t'as une tournure ADEME compatible ?
Par contre, tu peux aussi indiquer que "pas local" = "pas forcément de saison" du coup puisque ca peut être la saison en Nouvelle-Zélande (cerise), mais pas du tout celle de France métropolitaine.

**Comment by martinregner** [comment]
cf. #16 j'ai pris un texte de la page : https://agirpourlatransition.ademe.fr/collectivites/fiches/manger-bon-sain-local-territoire-comprendre
