### ISSUE TITLE
Ajout du score PEF

### ISSUE THREAD

**Issue by florianpanchout** [betagouv/ecolab-calculateur-fruits-et-legumes-de-saison#9]
J'ai ajouté le score PEF (ainsi qu'un texte d'explication) pour chaque produit.

**Comment by martinregner** [comment]
Je pense que le score PEF n'est pas très parlant (l'expérimentation sur l'affichage s'occupe de faire un "score" digne de ce nom d'un point de vue grand public), avis partagé en interne.

Sur la page, on parle plutôt CO2 et c'est un choix intéressant à conserver/généraliser : je te propose de plutôt aller chercher donc dans AGB la ligne en **kg CO2 eq/kg de produit** qui donnera quand même une info très intéressante

**Comment by florianpanchout** [comment]
C'est fait.

J'ai ajouté un indicateur rouge lorsque le kgCO2e/kg dépasse 1

**Comment by martinregner** [comment]
Parfait !! Ca rend très bien je trouve 👍
